blank_issues_enabled: false
contact_links:
  - name: OpsBeacon Support Email
    url: mailto:support@opsbeacon.com
    about: For urgent issues requiring immediate attention or cases where you need to share sensitive information, please email our support team.
  - name: OpsBeacon Documentation
    url: https://docs.opsbeacon.example.com
    about: Check our documentation for guides, tutorials, and API reference.
