name: Feature Request
description: Suggest a new feature or improvement for OpsBeacon
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # Feature Request
        Thanks for suggesting a new feature for OpsBeacon!
        
        **REMINDER: This is a public repository. DO NOT include sensitive information such as API keys, credentials, internal URLs, or customer data.**

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of the feature you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: problem-solving
    attributes:
      label: Problem This Feature Solves
      description: Describe the problem or limitation that this feature would address
      placeholder: Currently, it's difficult to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: This could be solved by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also thought about...
    validations:
      required: false

  - type: textarea
    id: user-impact
    attributes:
      label: User Impact
      description: How would this feature benefit users of the product?
      placeholder: This would help users to...
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas (Optional)
      description: If you have ideas about how to implement this feature, share them here
      placeholder: This might be implemented by...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Urgency
      description: How urgent is this feature for your use case?
      options:
        - Critical - Needed immediately
        - High - Needed in next release
        - Medium - Would be nice to have soon
        - Low - Nice to have eventually
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I'm willing to help implement this feature
        - label: I can help test this feature
        - label: I can provide more detailed requirements

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here
      placeholder: Any other details you think might be helpful...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **REMINDER: This is a public repository. DO NOT include sensitive information such as API keys, credentials, internal URLs, or customer data.**
